const cpaQuestions = [
  {
    category: "心肺蘇生",
    question: "呼吸と脈拍の確認は10秒以内に行う。",
    type: "ox",
    answer: "○",
    explanation: "呼吸・脈拍の確認は10秒以内に行う。",
  },
  {
    category: "心肺蘇生",
    question: "成人胸骨圧迫のテンポは100〜120回/分である。",
    type: "ox",
    answer: "○",
    explanation: "成人の胸骨圧迫テンポは100〜120回/分。",
  },
  {
    category: "心肺蘇生",
    question: "成人胸骨圧迫の深さは約5cmである。",
    type: "ox",
    answer: "○",
    explanation: "成人では約5cm沈むように圧迫する。",
  },
  {
    category: "心肺蘇生",
    question: "成人胸骨圧迫では6cmを超えないように行う。",
    type: "ox",
    answer: "○",
    explanation: "成人では約5cm、ただし6cmを超えないように行う。",
  },
  {
    category: "心肺蘇生",
    question: "成人CPRは胸骨圧迫30回、人工呼吸2回を1サイクルとする。",
    type: "ox",
    answer: "○",
    explanation: "成人CPRは30:2で実施する。",
  },
  {
    category: "心肺蘇生",
    question: "小児CPRは胸骨圧迫30回、人工呼吸2回を1サイクルとする。",
    type: "ox",
    answer: "×",
    explanation: "思春期以前の小児・乳児は15:2で実施する。",
  },
  {
    category: "心肺蘇生",
    question: "VFに対する対応として正しいものは？",
    type: "choice",
    choices: ["血糖測定", "除細動", "輸液", "搬送のみ"],
    answer: "除細動",
    explanation: "VF・無脈性VTは除細動適応。",
  },
  {
    category: "心肺蘇生",
    question: "PEAは除細動適応である。",
    type: "ox",
    answer: "×",
    explanation: "PEAは除細動適応ではない。",
  },
  {
    category: "心肺蘇生",
    question: "除細動1回実施後は直ちにCPRを再開する。",
    type: "ox",
    answer: "○",
    explanation: "除細動後は直ちにCPRを再開する。",
  },
  {
    category: "心肺蘇生",
    question: "CPR1ピリオドは約2分である。",
    type: "ox",
    answer: "○",
    explanation: "CPRは1ピリオド約2分で管理する。",
  }
,
  {
    category: "心肺蘇生",
    question: "Asystoleは除細動適応である。",
    type: "ox",
    answer: "×",
    explanation: "Asystoleは除細動適応ではない。",
  },
  {
    category: "心肺蘇生",
    question: "ROSC後も継続的な観察が必要である。",
    type: "ox",
    answer: "○",
    explanation: "ROSC後も再停止リスクがあるため観察継続。",
  },
  {
    category: "心肺蘇生",
    question: "PEAで重要なのはどれか。",
    type: "choice",
    choices: ["除細動", "原因検索", "経過観察", "搬送拒否"],
    answer: "原因検索",
    explanation: "PEAではH's and T'sの検索が重要。",
  },
  {
    category: "心肺蘇生",
    question: "胸骨圧迫中断は最小限にする。",
    type: "ox",
    answer: "○",
    explanation: "圧迫中断時間は最小限にする。",
  },
  {
    category: "心肺蘇生",
    question: "AED解析中は傷病者に接触しても良い。",
    type: "ox",
    answer: "×",
    explanation: "解析中は接触しない。",
  },
  {
    category: "心肺蘇生",
    question: "ROSC確認後に優先されるものは？",
    type: "choice",
    choices: ["搬送中止", "気道・呼吸循環管理", "除細動", "CPR中止のみ"],
    answer: "気道・呼吸循環管理",
    explanation: "ROSC後管理が重要。",
  },
  {
    category: "心肺蘇生",
    question: "CPA対応では質の高いCPRが重要である。",
    type: "ox",
    answer: "○",
    explanation: "高品質CPRが予後改善に重要。",
  },
  {
    category: "心肺蘇生",
    question: "VFはショック適応波形である。",
    type: "ox",
    answer: "○",
    explanation: "VFは除細動適応。",
  },
  {
    category: "心肺蘇生",
    question: "無脈性VTは除細動適応である。",
    type: "ox",
    answer: "○",
    explanation: "無脈性VTはショック適応。",
  },
  {
    category: "心肺蘇生",
    question: "CPA傷病者では酸素投与を考慮する。",
    type: "ox",
    answer: "○",
    explanation: "高濃度酸素投与を考慮する。",
  }];

export default cpaQuestions;