const dnarQuestions = [
  {
    category: "DNAR",
    question: "傷病者が明らかに死亡している場合は、DNARフローチャートの対象外である。",
    type: "ox",
    answer: "○",
    explanation: "明らかに死亡している場合は対象外。",
  },
  {
    category: "DNAR",
    question: "人生の最終段階とは、回復不可能な疾病の末期等にあることを指す。",
    type: "ox",
    answer: "○",
    explanation: "回復不可能な疾病の末期等を指す。",
  },
  {
    category: "DNAR",
    question: "心肺停止を確認したら、DNAR提示の有無に関わらず心肺蘇生等を開始する。",
    type: "ox",
    answer: "○",
    explanation: "提示の有無に関わらず、まず心肺蘇生等を開始する。",
  },
  {
    category: "DNAR",
    question: "判断に迷う場合は、心肺蘇生等の継続を優先し医療機関へ搬送する。",
    type: "ox",
    answer: "○",
    explanation: "迷う場合は心肺蘇生継続と搬送を優先する。",
  },
  {
    category: "DNAR",
    question: "救急隊側から積極的に傷病者の意思等を確認する必要がある。",
    type: "ox",
    answer: "×",
    explanation: "救急隊側から積極的に確認する必要はない。",
  },
  {
    category: "DNAR",
    question: "口頭でDNAR意思を伝えられた場合は、書面の有無を尋ねる。",
    type: "ox",
    answer: "○",
    explanation: "口頭で伝えられた場合は書面の有無を尋ねる。",
  },
  {
    category: "DNAR",
    question: "直ちに書面提示がない場合は、次のステップへ進む。",
    type: "ox",
    answer: "○",
    explanation: "直ちに書面提示がない場合は次のステップへ進む。",
  },
  {
    category: "DNAR",
    question: "外因性心肺停止とは交通事故、自傷、他害等を起因とした心肺停止を指す。",
    type: "ox",
    answer: "○",
    explanation: "交通事故、自傷、他害等が外因性心肺停止に含まれる。",
  },
  {
    category: "DNAR",
    question: "外因性心肺停止はDNARガイドラインの対象である。",
    type: "ox",
    answer: "×",
    explanation: "外因性CPAはDNAR対応の対象外。",
  },
  {
    category: "DNAR",
    question: "家族等が心肺蘇生等の継続を求める場合は、通常の心肺蘇生を継続し搬送する。",
    type: "ox",
    answer: "○",
    explanation: "家族等が継続を求める場合は通常蘇生を継続し搬送する。",
  },
  {
    category: "DNAR",
    question: "書面現物が現場で確認できない場合、かかりつけ医に存在確認できればよい。",
    type: "ox",
    answer: "○",
    explanation: "書面または診療録の存在をかかりつけ医に確認できればよい。",
  },
  {
    category: "DNAR",
    question: "家族のみで作成された書面でも、かかりつけ医署名がなくても有効書面とする。",
    type: "ox",
    answer: "×",
    explanation: "かかりつけ医署名がない場合は有効な意思確認書面としない。",
  },
  {
    category: "DNAR",
    question: "かかりつけ医に連絡がつかない場合、活動開始から何分程度を目途に判断するか。",
    type: "choice",
    choices: ["5分程度", "10分程度", "30分程度", "60分程度"],
    answer: "10分程度",
    explanation: "活動開始から10分程度を目途に搬送か連絡継続か判断する。",
  },
  {
    category: "DNAR",
    question: "オンラインMC医には、原則として傷病者意思確認や心肺蘇生中止の是非判断を求める。",
    type: "ox",
    answer: "×",
    explanation: "原則としてオンラインMC医に意思確認や中止の是非判断を求めない。",
  },
  {
    category: "DNAR",
    question: "かかりつけ医は心肺蘇生中止の是非を判断し、救急隊へ指示を伝える。",
    type: "ox",
    answer: "○",
    explanation: "連絡を受けたかかりつけ医が中止の是非を判断し指示する。",
  },
  {
    category: "DNAR",
    question: "心肺蘇生等の中止は死亡診断を意味する。",
    type: "ox",
    answer: "×",
    explanation: "中止は処置の中止であり、死亡診断を意味しない。",
  },
  {
    category: "DNAR",
    question: "かかりつけ医以外の医療従事者からの伝聞指示も、中止指示として扱う。",
    type: "ox",
    answer: "×",
    explanation: "伝聞による指示は、かかりつけ医からの中止指示とはみなさない。",
  },
  {
    category: "DNAR",
    question: "医療機関への不搬送等同意書は、家族等への引き継ぎ時に使用する。",
    type: "ox",
    answer: "○",
    explanation: "不搬送等同意書を使用する。",
  },
  {
    category: "DNAR",
    question: "不搬送等同意書の原本は消防本部が保管する。",
    type: "ox",
    answer: "○",
    explanation: "原本は消防本部が保管し、必要に応じて写しを交付する。",
  },
  {
    category: "DNAR",
    question: "DNAR対応で迷った場合の原則として正しいものはどれか。",
    type: "choice",
    choices: [
      "心肺蘇生を中止する",
      "心肺蘇生を継続し搬送する",
      "家族判断のみで不搬送",
      "オンラインMC医に死亡診断を求める"
    ],
    answer: "心肺蘇生を継続し搬送する",
    explanation: "判断に迷う場合は心肺蘇生等の継続と搬送を優先する。",
  },
];

export default dnarQuestions;