const preCpaQuestions = [
  {
    category: "心肺停止前",
    question: "エピペンは、本人が使用困難な場合に救急救命士が実施する。",
    type: "ox",
    answer: "○",
    explanation: "処方・所持確認があり、本人が使用困難な場合に実施する。",
  },
  {
    category: "心肺停止前",
    question: "エピペン実施には、エピペンの処方があることが必須事項である。",
    type: "ox",
    answer: "○",
    explanation: "必須事項としてエピペンの処方ありとされている。",
  },
  {
    category: "心肺停止前",
    question: "アナフィラキシー疑いは、基本的に2つ以上の臓器症状を確認する。",
    type: "ox",
    answer: "○",
    explanation: "基本は2つ以上の臓器に症状が現れたものとされる。",
  },
  {
    category: "心肺停止前",
    question: "ショック症状が改善しなければ、心肺停止前の静脈路確保と輸液プロトコールへ移行する。",
    type: "ox",
    answer: "○",
    explanation: "エピペン後も改善しなければ輸液プロトコールへ移行する。",
  },
  {
    category: "心肺停止前",
    question: "心肺停止前の静脈路確保と輸液の対象年齢は？",
    type: "choice",
    choices: ["10歳以上", "12歳以上", "15歳以上", "18歳以上"],
    answer: "15歳以上",
    explanation: "対象は15歳以上、推定を含む。",
  },
  {
    category: "心肺停止前",
    question: "心原性ショックが強く疑われる傷病者は、心肺停止前輸液の対象除外である。",
    type: "ox",
    answer: "○",
    explanation: "心原性ショックが強く疑われる場合は対象除外。",
  },
  {
    category: "心肺停止前",
    question: "心肺停止前の静脈路確保は、救急車内での実施を優先する。",
    type: "ox",
    answer: "○",
    explanation: "救急車内で実施することを優先する。",
  },
  {
    category: "心肺停止前",
    question: "心肺停止前の静脈路確保で、静脈が触認できない場合も必ず穿刺する。",
    type: "ox",
    answer: "×",
    explanation: "静脈が触認できない場合は実施しない。",
  },
  {
    category: "心肺停止前",
    question: "心肺停止前静脈路確保の穿刺試行は1回90秒以内を目途とする。",
    type: "ox",
    answer: "○",
    explanation: "穿刺試行は1回90秒以内を目途とする。",
  },
  {
    category: "心肺停止前",
    question: "心肺停止前静脈路確保の穿刺回数は原則何回まで？",
    type: "choice",
    choices: ["1回", "2回", "3回", "制限なし"],
    answer: "2回",
    explanation: "穿刺回数は原則2回まで。",
  },
  {
    category: "心肺停止前",
    question: "心肺停止前輸液は急速輸液を原則とするが、医師の指示があればそれに従う。",
    type: "ox",
    answer: "○",
    explanation: "急速輸液を原則とし、医師の指示があれば従う。",
  },
  {
    category: "心肺停止前",
    question: "心肺停止状態へ変化した場合は、心肺停止プロトコールへ移行する。",
    type: "ox",
    answer: "○",
    explanation: "CPAへ容態変化した場合は心肺停止プロトコールへ移行する。",
  },
  {
    category: "心肺停止前",
    question: "血糖測定の対象年齢は15歳以上である。",
    type: "ox",
    answer: "○",
    explanation: "血糖測定・ブドウ糖投与プロトコールは15歳以上が対象。",
  },
  {
    category: "心肺停止前",
    question: "血糖測定の対象は、意識レベルJCS10以上を目安とする。",
    type: "ox",
    answer: "○",
    explanation: "意識レベルJCS10以上を目安とする。",
  },
  {
    category: "心肺停止前",
    question: "低血糖発作症例でブドウ糖投与を考慮する血糖値は？",
    type: "choice",
    choices: ["50mg/dl未満", "70mg/dl未満", "90mg/dl未満", "120mg/dl未満"],
    answer: "50mg/dl未満",
    explanation: "BS＜50mg/dlでブドウ糖投与を考慮する。",
  },
  {
    category: "心肺停止前",
    question: "50％ブドウ糖溶液の投与量は40mlを原則とする。",
    type: "ox",
    answer: "○",
    explanation: "50％ブドウ糖溶液40mlを原則とする。",
  },
  {
    category: "心肺停止前",
    question: "50％ブドウ糖溶液40mlは概ね3〜4分かけて投与する。",
    type: "ox",
    answer: "○",
    explanation: "概ね3〜4分かけてゆっくり投与する。",
  },
  {
    category: "心肺停止前",
    question: "ブドウ糖投与後、約3分後の意識レベル評価を慎重に行う。",
    type: "ox",
    answer: "○",
    explanation: "投与後約3分後の意識レベル評価を行う。",
  },
  {
    category: "心肺停止前",
    question: "血糖測定では、くも膜下出血が疑われる場合でも皮膚穿刺は必ず実施する。",
    type: "ox",
    answer: "×",
    explanation: "痛み刺激が不適切と考えられる場合は除外する。",
  },
  {
    category: "心肺停止前",
    question: "ブドウ糖投与で意識レベルが改善した場合、搬送先医療機関の再考をしてもよい。",
    type: "ox",
    answer: "○",
    explanation: "意識改善時は医師へ報告し、搬送先を再考してもよい。",
  },
];

export default preCpaQuestions;